/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/13/2022-05:54.
 * Please do not change it manually.
 */

#ifndef _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CV_C_IMGCODECS_H_
#define _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CV_C_IMGCODECS_H_

#include <DocumentScannerFramework/c_helpers.h>

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    
    CppBindCObject _func_Cv_imread_1(char* _Nonnull filename, CppBindCObject* _Nonnull cppbind_err);

    CppBindCObject _func_Cv_imread(char* _Nonnull filename, int  flags, CppBindCObject* _Nonnull cppbind_err);
#if __cplusplus
}
#endif
#endif /* ifndef _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CV_C_IMGCODECS_H_ */
