/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/14/2022-07:21.
 * Please do not change it manually.
 */

#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <cxxabi.h>
#include <memory>
#include <type_traits>
#include "document_scanner/api/ios/DocumentScannerFramework/DocumentScannerFramework/Cpp/cv/c_mat.h"
#include <opencv2/opencv.hpp>


extern const char* CPPBIND_STD_STDEXCEPTION;

const char* CPPBIND_CV_MAT = "cv::Mat";

using namespace cv;

void release_Cv_Mat(CppBindCObject cself, bool owner) {
    if (owner) {
        delete static_cast<cv::Mat*>(cself.ptr);
    }
    free(cself.type);
}

CppBindCObject create_Cv_Mat(CppBindCObject* _Nonnull cppbind_err) {
    try {
        auto this_object = new cv::Mat();
        return {strdup(CPPBIND_CV_MAT), this_object};
    } catch (const std::exception& e) {
        cppbind_err->type = strdup(CPPBIND_STD_STDEXCEPTION);
        cppbind_err->ptr = new std::exception(e);
    } catch (...) {
        cppbind_err->type = strdup("Uncaught Exception");
    }
    CppBindCObject result {};
    return result;
}

