/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/14/2022-07:21.
 * Please do not change it manually.
 */

#ifndef _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CV_C_TYPES_H_
#define _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CV_C_TYPES_H_

#include <DocumentScannerFramework/c_helpers.h>

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_Cv_PointInt(CppBindCObject cself, bool owner);
    void release_Cv_PointFloat(CppBindCObject cself, bool owner);
#if __cplusplus
}
#endif
#endif /* ifndef _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CV_C_TYPES_H_ */
