/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/14/2022-07:21.
 * Please do not change it manually.
 */

#ifndef _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_DOC_SCANNER_C_DOCUMENT_SCANNER_CV_H_
#define _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_DOC_SCANNER_C_DOCUMENT_SCANNER_CV_H_

#include <DocumentScannerFramework/c_helpers.h>

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_DocCornerPointsExtractor(CppBindCObject cself, bool owner);

    CppBindCObject create_DocCornerPointsExtractor(CppBindCObject* _Nonnull cppbind_err);

    CppBindCObject create_DocCornerPointsExtractor_1(CppBindCObject image, CppBindCObject* _Nonnull cppbind_err);
    CppBindCObject _prop_get_DocCornerPointsExtractor_image(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);

    void _prop_set_DocCornerPointsExtractor_image(CppBindCObject cself, CppBindCObject image, CppBindCObject* _Nonnull cppbind_err);

    void _func_DocCornerPointsExtractor_computeCornerPoints(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
    CppBindCDataArray _prop_get_DocCornerPointsExtractor_points(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
    void release_DocExtractor(CppBindCObject cself, bool owner);

    CppBindCObject create_DocExtractor(CppBindCObject image, CppBindCDataArray doc_corner_points, float w, float h, int margin, CppBindCObject* _Nonnull cppbind_err);
    CppBindCObject _prop_get_DocExtractor_image(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);

    void _prop_set_DocExtractor_image(CppBindCObject cself, CppBindCObject image, CppBindCObject* _Nonnull cppbind_err);

    CppBindCObject _func_DocExtractor_warp(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
    CppBindCObject _func_DocExtractor_drawPoints(CppBindCObject cself, int  r, int  g, int  b, CppBindCObject* _Nonnull cppbind_err);

    bool _func__saveImage(char* _Nonnull filename, CppBindCObject  img, CppBindCObject* _Nonnull cppbind_err);
#if __cplusplus
}
#endif
#endif /* ifndef _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_DOC_SCANNER_C_DOCUMENT_SCANNER_CV_H_ */
