/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/08/2022-16:07.
 * Please do not change it manually.
 */

package cv

import cppbind.alias.*
import cppbind.exceptionUtils.*
import cppbind.exception_helpers.*

enum class ImreadModes(val value: Int) {
    /**
     * < If set, return the loaded image as is (with alpha channel, otherwise it gets cropped). Ignore EXIF orientation.
     */
    IMREAD_UNCHANGED(-1),
    /**
     * < If set, always convert image to the single channel grayscale image (codec internal conversion).
     */
    IMREAD_GRAYSCALE(0),
    /**
     * < If set, always convert image to the 3 channel BGR color image.
     */
    IMREAD_COLOR(1),
    /**
     * < If set, return 16-bit/32-bit image when the input has the corresponding depth, otherwise convert it to 8-bit.
     */
    IMREAD_ANYDEPTH(2),
    /**
     * < If set, the image is read in any possible color format.
     */
    IMREAD_ANYCOLOR(4),
    /**
     * < If set, use the gdal driver for loading the image.
     */
    IMREAD_LOAD_GDAL(8),
    /**
     * < If set, always convert image to the single channel grayscale image and the image size reduced 1/2.
     */
    IMREAD_REDUCED_GRAYSCALE_2(16),
    /**
     * < If set, always convert image to the 3 channel BGR color image and the image size reduced 1/2.
     */
    IMREAD_REDUCED_COLOR_2(17),
    /**
     * < If set, always convert image to the single channel grayscale image and the image size reduced 1/4.
     */
    IMREAD_REDUCED_GRAYSCALE_4(32),
    /**
     * < If set, always convert image to the 3 channel BGR color image and the image size reduced 1/4.
     */
    IMREAD_REDUCED_COLOR_4(33),
    /**
     * < If set, always convert image to the single channel grayscale image and the image size reduced 1/8.
     */
    IMREAD_REDUCED_GRAYSCALE_8(64),
    /**
     * < If set, always convert image to the 3 channel BGR color image and the image size reduced 1/8.
     */
    IMREAD_REDUCED_COLOR_8(65),
    /**
     * < If set, do not rotate the image according to EXIF's orientation flag.
     */
    IMREAD_IGNORE_ORIENTATION(128);

    companion object {
        private val values = values()
        fun getByValue(value: Int) = values.firstOrNull { it.value == value }
    }
}

fun imread(filename: String): Mat {
    val result = jImread_1(filename)
    val jdktokotlinresult = Mat(CppBindObject(result, true))
    return jdktokotlinresult
}


fun imread(filename: String, flags: Int): Mat {
    val result = jImread(filename, flags)
    val jdktokotlinresult = Mat(CppBindObject(result, true))
    return jdktokotlinresult
}

private external fun jImread_1(filename: String, vararg extraObjs: Any?): Long

private external fun jImread(filename: String, flags: Int, vararg extraObjs: Any?): Long

private external fun jGettypebyid(id: Long): String
