/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/14/2022-07:21.
 * Please do not change it manually.
 */

#ifndef _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CPPBIND_EXCEPTION_HELPERS_C_STD_EXC_CLASSES_H_
#define _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CPPBIND_EXCEPTION_HELPERS_C_STD_EXC_CLASSES_H_

#include <DocumentScannerFramework/c_helpers.h>

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_Std_StdException(CppBindCObject cself, bool owner);
    const char * _Nonnull _func_Std_StdException_what(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
#if __cplusplus
}
#endif
#endif /* ifndef _DOCUMENT_SCANNER_API_IOS_DOCUMENTSCANNERFRAMEWORK_DOCUMENTSCANNERFRAMEWORK_CPP_CPPBIND_EXCEPTION_HELPERS_C_STD_EXC_CLASSES_H_ */
